### ISSUE TITLE
AttributeError: 'Functional' object has no attribute 'total_loss'

### ISSUE THREAD

**Issue by cicilzx** [shiningrain/AUTOTRAINER#2]
Hello! I'm running the demo.py file and I got this message:
Traceback (most recent call last):
  File "E:/Code/AutoTrainer/demo_case/Gradient_Vanish_Case/demo.py", line 84, in <module>
    new_issue_dir=new_issue_dir,root_path=root_path)
  File "E:\Code\AutoTrainer\utils\util.py", line 381, in model_train
    dataset['x_val'], dataset['y_val']), epochs=iters, verbose=verb, callbacks=callbacks_new)
  File "E:\anaconda3\envs\dnn_repair\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1080, in fit
    callbacks.on_train_begin()
  File "E:\anaconda3\envs\dnn_repair\lib\site-packages\tensorflow\python\keras\callbacks.py", line 515, in on_train_begin
    callback.on_train_begin(numpy_logs)
  File "E:\Code\AutoTrainer\utils\util.py", line 99, in on_train_begin
    grads = self.model.optimizer.get_gradients(self.model.total_loss, weights)
AttributeError: 'Functional' object has no attribute 'total_loss'

I'm using keras==2.4.3 and tensorflow-gpu==2.4.0.
Thanks a lot for your help!

**Comment by shiningrain** [comment]
Hello! 
The problem seems to be caused by the changed version of TensorFlow.  In higher versions, some attributes of the objects may be changed in TF. It seems that the `total loss` attribute was removed from the `model` object in TF-2.4.
As shown in `requirements.txt` in this repo, our code is implemented on `keras=2.3.1` and `tensorflow=2.1.0`. I personally suggest that you can lower the version of TensorFlow.
We are also planning to improve the code to assist the system to be compatible with higher versions of TF recently.

**Comment by cicilzx** [comment]
> Hello! The problem seems to be caused by the changed version of TensorFlow. In higher versions, some attributes of the objects may be changed in TF. It seems that the `total loss` attribute was removed from the `model` object in TF-2.4. As shown in `requirements.txt` in this repo, our code is implemented on `keras=2.3.1` and `tensorflow=2.1.0`. I personally suggest that you can lower the version of TensorFlow. We are also planning to improve the code to assist the system to be compatible with higher versions of TF recently.

Yeah! I have changed my tensorflow version, and now it's working! Thank you so much!
