### ISSUE TITLE
Crash with LSTM/GRU programs

### ISSUE THREAD

**Issue by arbab-isu** [shiningrain/AUTOTRAINER#3]
Hello, I hope you are doing well. Thank you for your work on AutoTrainer. 
I have been able to run your program successfully on your benchmark and I am currently trying to run it on custom LSTM/GRU models. However it is giving me this error at:
Line 71 in utils/monitor.py 
Statement: assert len(gradient_list)%2==0 
Error: AssertionError
Could you please tell me what the purpose of this line is? so that I can debug it? 
It runs fine on few such programs but crashes with the above error on few.

<img width="1390" alt="Screen Shot 2022-07-28 at 9 19 01 PM" src="https://user-images.githubusercontent.com/100961949/181669123-d54efec7-5c97-4eb4-a99a-f78201c93cbb.png">

thanks, 

Link : https://github.com/shiningrain/AUTOTRAINER/blob/master/AutoTrainer/utils/monitor.py#:~:text=(gradient_list)%3A-,assert,-len(gradient_list

**Comment by arbab-isu** [comment]
@shiqingma I'll appreciate your help on it. Thank you,

**Comment by shiningrain** [comment]
Hi @arbab-isu, thank you very much for using AutoTrainer and for your valuable comments.

The issue has been confirmed to come from the undeleted debug codes in the recent commits of the `Test-Master` branch, and I will fix it later.
Since we are updating the functionality of AutoTrainer, we have recently set up two branches. The `Stable-Master` branch provides code and features for our early experiments, and the `Test-Master` contains the modifications and debugging of the current latest version (which may have similar issues).
You can change the branch to the stable version.

> Hello, I hope you are doing well. Thank you for your work on AutoTrainer. I have been able to run your program successfully on your benchmark and I am currently trying to run it on custom LSTM/GRU models. However it is giving me this error at: Line 71 in utils/monitor.py Statement: assert len(gradient_list)%2==0 Error: AssertionError Could you please tell me what the purpose of this line is? so that I can debug it? It runs fine on few such programs but crashes with the above error on few.
> 
> <img alt="Screen Shot 2022-07-28 at 9 19 01 PM" width="1390" src="https://user-images.githubusercontent.com/100961949/181669123-d54efec7-5c97-4eb4-a99a-f78201c93cbb.png">
> 
> thanks,
> 
> Link : https://github.com/shiningrain/AUTOTRAINER/blob/master/AutoTrainer/utils/monitor.py#:~:text=(gradient_list)%3A-,assert,-len(gradient_list

**Comment by arbab-isu** [comment]
@shiningrain thank you for your comments. 
Highly appreciated. thanks,
